/**
 * Demo Mode Seeder
 * Pre-populates the demo storage with 1000+ realistic patient records
 */

import { demoStorage } from '../services/demo-storage.service';
import logger from '../config/logger';
// uuid import removed — patient IDs are generated by index

// ==================== DATA POOLS ====================

const CONDITIONS_POOL = [
    { name: 'Hypertension', category: 'Cardiovascular', severity: ['mild', 'moderate', 'severe'], prevalence: 0.32 },
    { name: 'Coronary Artery Disease', category: 'Cardiovascular', severity: ['moderate', 'severe'], prevalence: 0.06 },
    { name: 'Heart Failure', category: 'Cardiovascular', severity: ['moderate', 'severe'], prevalence: 0.03 },
    { name: 'Atrial Fibrillation', category: 'Cardiovascular', severity: ['mild', 'moderate'], prevalence: 0.02 },
    { name: 'Type 2 Diabetes', category: 'Endocrine', severity: ['mild', 'moderate', 'severe'], prevalence: 0.1 },
    { name: 'Hypothyroidism', category: 'Endocrine', severity: ['mild', 'moderate'], prevalence: 0.05 },
    { name: 'Hyperlipidemia', category: 'Metabolic', severity: ['mild', 'moderate'], prevalence: 0.27 },
    { name: 'Asthma', category: 'Respiratory', severity: ['mild', 'moderate', 'severe'], prevalence: 0.08 },
    { name: 'COPD', category: 'Respiratory', severity: ['moderate', 'severe'], prevalence: 0.06 },
    { name: 'Chronic Kidney Disease Stage 2', category: 'Renal', severity: ['mild'], prevalence: 0.04 },
    { name: 'Chronic Kidney Disease Stage 3', category: 'Renal', severity: ['moderate'], prevalence: 0.03 },
    { name: 'Chronic Kidney Disease Stage 4', category: 'Renal', severity: ['severe'], prevalence: 0.01 },
    { name: 'GERD', category: 'Gastrointestinal', severity: ['mild', 'moderate'], prevalence: 0.2 },
    { name: 'Peptic Ulcer Disease', category: 'Gastrointestinal', severity: ['mild', 'moderate'], prevalence: 0.04 },
    { name: 'Major Depressive Disorder', category: 'Psychiatric', severity: ['mild', 'moderate', 'severe'], prevalence: 0.07 },
    { name: 'Generalized Anxiety Disorder', category: 'Psychiatric', severity: ['mild', 'moderate'], prevalence: 0.06 },
    { name: 'Insomnia', category: 'Psychiatric', severity: ['mild', 'moderate'], prevalence: 0.1 },
    { name: 'Osteoarthritis', category: 'Musculoskeletal', severity: ['mild', 'moderate', 'severe'], prevalence: 0.1 },
    { name: 'Rheumatoid Arthritis', category: 'Musculoskeletal', severity: ['moderate', 'severe'], prevalence: 0.01 },
    { name: 'Osteoporosis', category: 'Musculoskeletal', severity: ['mild', 'moderate'], prevalence: 0.05 },
    { name: 'Migraine', category: 'Neurological', severity: ['mild', 'moderate'], prevalence: 0.12 },
    { name: 'Peripheral Neuropathy', category: 'Neurological', severity: ['mild', 'moderate'], prevalence: 0.02 },
    { name: 'Benign Prostatic Hyperplasia', category: 'Urological', severity: ['mild', 'moderate'], prevalence: 0.15 },
    { name: 'Erectile Dysfunction', category: 'Urological', severity: ['mild', 'moderate', 'severe'], prevalence: 0.18 },
];

const MEDICATIONS_POOL = [
    { name: 'Lisinopril', genericName: 'lisinopril', dosages: ['5mg', '10mg', '20mg', '40mg'], frequencies: ['QD'] },
    { name: 'Metoprolol', genericName: 'metoprolol', dosages: ['25mg', '50mg', '100mg'], frequencies: ['QD', 'BID'] },
    { name: 'Amlodipine', genericName: 'amlodipine', dosages: ['2.5mg', '5mg', '10mg'], frequencies: ['QD'] },
    { name: 'Atorvastatin', genericName: 'atorvastatin', dosages: ['10mg', '20mg', '40mg', '80mg'], frequencies: ['QD'] },
    { name: 'Aspirin', genericName: 'aspirin', dosages: ['81mg', '325mg'], frequencies: ['QD'] },
    { name: 'Warfarin', genericName: 'warfarin', dosages: ['2mg', '5mg', '7.5mg'], frequencies: ['QD'] },
    { name: 'Nitroglycerin', genericName: 'nitroglycerin', dosages: ['0.4mg'], frequencies: ['PRN'] },
    { name: 'Metformin', genericName: 'metformin', dosages: ['500mg', '850mg', '1000mg'], frequencies: ['QD', 'BID'] },
    { name: 'Glipizide', genericName: 'glipizide', dosages: ['5mg', '10mg'], frequencies: ['QD', 'BID'] },
    { name: 'Jardiance', genericName: 'empagliflozin', dosages: ['10mg', '25mg'], frequencies: ['QD'] },
    { name: 'Omeprazole', genericName: 'omeprazole', dosages: ['20mg', '40mg'], frequencies: ['QD', 'BID'] },
    { name: 'Pantoprazole', genericName: 'pantoprazole', dosages: ['20mg', '40mg'], frequencies: ['QD'] },
    { name: 'Sertraline', genericName: 'sertraline', dosages: ['25mg', '50mg', '100mg', '150mg'], frequencies: ['QD'] },
    { name: 'Escitalopram', genericName: 'escitalopram', dosages: ['5mg', '10mg', '20mg'], frequencies: ['QD'] },
    { name: 'Trazodone', genericName: 'trazodone', dosages: ['50mg', '100mg', '150mg'], frequencies: ['QHS'] },
    { name: 'Alprazolam', genericName: 'alprazolam', dosages: ['0.25mg', '0.5mg', '1mg'], frequencies: ['PRN', 'TID'] },
    { name: 'Gabapentin', genericName: 'gabapentin', dosages: ['100mg', '300mg', '400mg', '600mg'], frequencies: ['TID'] },
    { name: 'Meloxicam', genericName: 'meloxicam', dosages: ['7.5mg', '15mg'], frequencies: ['QD'] },
    { name: 'Albuterol', genericName: 'albuterol', dosages: ['90mcg'], frequencies: ['PRN'] },
    { name: 'Montelukast', genericName: 'montelukast', dosages: ['10mg'], frequencies: ['QD'] },
    { name: 'Levothyroxine', genericName: 'levothyroxine', dosages: ['25mcg', '50mcg', '75mcg', '100mcg', '125mcg'], frequencies: ['QD'] },
    { name: 'Tamsulosin', genericName: 'tamsulosin', dosages: ['0.4mg'], frequencies: ['QD'] },
    { name: 'Finasteride', genericName: 'finasteride', dosages: ['5mg'], frequencies: ['QD'] },
];

const ALLERGENS_POOL = [
    { name: 'Penicillin', reactions: ['Rash', 'Hives', 'Anaphylaxis'], severities: ['mild', 'severe', 'anaphylaxis'] },
    { name: 'Sulfa drugs', reactions: ['Rash', 'Stevens-Johnson syndrome'], severities: ['mild', 'severe'] },
    { name: 'NSAIDs', reactions: ['GI bleeding', 'Bronchospasm'], severities: ['mild', 'severe'] },
    { name: 'Aspirin', reactions: ['GI upset', 'Asthma exacerbation'], severities: ['mild', 'moderate'] },
    { name: 'Codeine', reactions: ['Nausea', 'Respiratory depression'], severities: ['mild', 'severe'] },
    { name: 'Shellfish', reactions: ['Hives', 'Anaphylaxis'], severities: ['mild', 'severe', 'anaphylaxis'] },
    { name: 'Peanuts', reactions: ['Swelling', 'Anaphylaxis'], severities: ['moderate', 'severe', 'anaphylaxis'] },
    { name: 'Latex', reactions: ['Contact dermatitis', 'Anaphylaxis'], severities: ['mild', 'severe'] },
    { name: 'Contrast dye', reactions: ['Flushing', 'Anaphylaxis'], severities: ['mild', 'severe'] },
];

const CHIEF_COMPLAINTS = [
    { complaint: 'Erectile dysfunction - difficulty achieving and maintaining erection', durations: ['3 months', '6 months', '1 year', '2 years'] },
    { complaint: 'Hair loss - progressive thinning and male pattern baldness', durations: ['6 months', '1 year', '2 years', '5 years'] },
    { complaint: 'Weight gain - difficulty losing weight despite diet changes', durations: ['6 months', '1 year', '2 years'] },
    { complaint: 'Chest pain - intermittent discomfort with exertion', durations: ['1 week', '1 month', '3 months'] },
    { complaint: 'Shortness of breath with minimal activity', durations: ['1 week', '1 month', '3 months'] },
    { complaint: 'Joint pain and stiffness in multiple joints', durations: ['1 month', '3 months', '6 months', '1 year'] },
    { complaint: 'Chronic fatigue and lack of energy', durations: ['1 month', '3 months', '6 months'] },
    { complaint: 'Difficulty sleeping and frequent waking', durations: ['1 month', '3 months', '6 months', '1 year'] },
    { complaint: 'Frequent headaches interfering with daily activities', durations: ['1 week', '1 month', '3 months'] },
    { complaint: 'Anxiety and excessive worry affecting daily life', durations: ['1 month', '3 months', '6 months'] },
    { complaint: 'Depression with low mood and loss of interest', durations: ['1 month', '3 months', '6 months', '1 year'] },
    { complaint: 'Urinary frequency and urgency', durations: ['1 month', '3 months', '6 months'] },
];

const SURGERIES_POOL = [
    'Appendectomy', 'Cholecystectomy', 'Coronary artery bypass graft', 'Total knee replacement',
    'Total hip replacement', 'Hysterectomy', 'Cataract surgery', 'Hernia repair',
    'Tonsillectomy', 'Prostatectomy', 'Cesarean section', 'Lumpectomy',
];

const FAMILY_CONDITIONS = [
    'Heart disease (father)', 'Heart disease (mother)', 'Type 2 Diabetes (father)',
    'Type 2 Diabetes (mother)', 'Breast cancer (mother)', 'Colon cancer (father)',
    'Stroke (grandfather)', 'Hypertension (multiple family members)',
    'Alzheimers disease (grandmother)', 'Prostate cancer (father)',
];

const PRESCRIBERS = [
    'Primary Care Physician', 'Cardiologist', 'Endocrinologist', 'Internist',
    'Pulmonologist', 'Gastroenterologist', 'Psychiatrist', 'Neurologist',
];

// ==================== UTILITY FUNCTIONS ====================

function randomChoice<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
}

function randomInt(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomFloat(min: number, max: number, decimals = 1): number {
    return Number.parseFloat((Math.random() * (max - min) + min).toFixed(decimals));
}

function formatDate(date: Date): string {
    return date.toISOString().split('T')[0];
}

function shouldOccur(probability: number): boolean {
    return Math.random() < probability;
}

// ==================== PATIENT GENERATOR (EXTRACTED HELPERS) ====================

function generateConditions(age: number, bmi: number) {
    const conditions: Array<{ condition: string; diagnosisDate: string; severity: string; controlled: boolean }> = [];
    const conditionProbabilityMultiplier = 1 + (age - 40) / 100 + (bmi - 25) / 50;
    for (const condition of CONDITIONS_POOL) {
        const adjustedProbability = Math.min(0.9, condition.prevalence * conditionProbabilityMultiplier);
        if (!shouldOccur(adjustedProbability)) continue;
        const yearsAgo = randomInt(1, Math.min(20, age - 18));
        conditions.push({
            condition: condition.name,
            diagnosisDate: formatDate(new Date(Date.now() - yearsAgo * 365 * 24 * 60 * 60 * 1000)),
            severity: randomChoice(condition.severity),
            controlled: shouldOccur(0.7),
        });
    }
    return conditions;
}

function generateAllergies() {
    const allergies: Array<{ allergen: string; reaction: string; severity: string }> = [];
    if (!shouldOccur(0.25)) return allergies;
    const allergyCount = randomInt(1, 3);
    const shuffled = [...ALLERGENS_POOL].sort(() => Math.random() - 0.5);
    for (let i = 0; i < allergyCount && i < shuffled.length; i++) {
        allergies.push({
            allergen: shuffled[i].name,
            reaction: randomChoice(shuffled[i].reactions),
            severity: randomChoice(shuffled[i].severities),
        });
    }
    return allergies;
}

function generateSurgeries() {
    const surgeries: Array<{ procedure: string; date: string }> = [];
    if (!shouldOccur(0.3)) return surgeries;
    const surgeryCount = randomInt(1, 2);
    const shuffled = [...SURGERIES_POOL].sort(() => Math.random() - 0.5);
    for (let i = 0; i < surgeryCount && i < shuffled.length; i++) {
        const surgeryYear = randomInt(2000, 2023);
        surgeries.push({
            procedure: shuffled[i],
            date: formatDate(new Date(surgeryYear, randomInt(0, 11), randomInt(1, 28))),
        });
    }
    return surgeries;
}

function generateFamilyHistory() {
    const familyHistory: string[] = [];
    if (!shouldOccur(0.6)) return familyHistory;
    const historyCount = randomInt(1, 3);
    const shuffled = [...FAMILY_CONDITIONS].sort(() => Math.random() - 0.5);
    for (let i = 0; i < historyCount && i < shuffled.length; i++) {
        familyHistory.push(shuffled[i]);
    }
    return familyHistory;
}

type MedicationEntry = {
    drugName: string; genericName: string; dosage: string;
    frequency: string; route: string; startDate: string; prescribedBy: string;
};

function addMedToList(medications: MedicationEntry[], name: string) {
    const med = MEDICATIONS_POOL.find(m => m.name === name);
    if (!med) return;
    medications.push({
        drugName: med.name, genericName: med.genericName,
        dosage: randomChoice(med.dosages), frequency: randomChoice(med.frequencies),
        route: 'oral',
        startDate: formatDate(new Date(randomInt(2020, 2023), randomInt(0, 11), randomInt(1, 28))),
        prescribedBy: randomChoice(PRESCRIBERS),
    });
}

const CONDITION_MED_MAP: Array<{ matcher: (c: string) => boolean; meds: Array<{ name: string; probability: number }> }> = [
    { matcher: c => c.includes('hypertension'), meds: [{ name: 'Lisinopril', probability: 0.8 }, { name: 'Amlodipine', probability: 0.5 }, { name: 'Metoprolol', probability: 0.4 }] },
    { matcher: c => c.includes('diabetes'), meds: [{ name: 'Metformin', probability: 0.9 }, { name: 'Glipizide', probability: 0.3 }, { name: 'Jardiance', probability: 0.2 }] },
    { matcher: c => c.includes('coronary') || c.includes('heart'), meds: [{ name: 'Aspirin', probability: 0.9 }, { name: 'Atorvastatin', probability: 0.7 }, { name: 'Metoprolol', probability: 0.4 }, { name: 'Nitroglycerin', probability: 0.3 }] },
    { matcher: c => c.includes('hyperlipidemia'), meds: [{ name: 'Atorvastatin', probability: 0.9 }] },
    { matcher: c => c.includes('depression') || c.includes('anxiety'), meds: [{ name: randomChoice(['Sertraline', 'Escitalopram']), probability: 0.7 }] },
    { matcher: c => c.includes('gerd'), meds: [{ name: 'Omeprazole', probability: 0.8 }] },
    { matcher: c => c.includes('hypothyroid'), meds: [{ name: 'Levothyroxine', probability: 0.95 }] },
    { matcher: c => c.includes('prostatic'), meds: [{ name: 'Tamsulosin', probability: 0.8 }, { name: 'Finasteride', probability: 0.4 }] },
];

function generateMedications(conditionNames: string[]): MedicationEntry[] {
    const medications: MedicationEntry[] = [];
    for (const mapping of CONDITION_MED_MAP) {
        if (!conditionNames.some(mapping.matcher)) continue;
        for (const med of mapping.meds) {
            if (shouldOccur(med.probability)) addMedToList(medications, med.name);
        }
    }
    return medications;
}

function getAlcoholDrinksPerWeek(alcoholFrequency: string): number | undefined {
    if (alcoholFrequency === 'never') return undefined;
    const maxDrinks = alcoholFrequency === 'heavy' ? 28 : 14;
    return randomInt(1, maxDrinks);
}

function generateLifestyle() {
    const smokingStatus = randomChoice(['never', 'never', 'never', 'former', 'former', 'current']);
    const alcoholFrequency = randomChoice(['never', 'rarely', 'occasionally', 'moderate', 'heavy']);
    const exerciseFrequency = randomChoice(['sedentary', 'light', 'moderate', 'active']);
    const dietOptions = ['standard', 'low_sodium', 'diabetic', 'mediterranean', 'vegetarian', 'low_carb'];
    const complaintData = randomChoice(CHIEF_COMPLAINTS);

    return {
        smokingStatus,
        smokingPacksPerDay: smokingStatus === 'current' ? randomFloat(0.5, 2, 1) : undefined,
        smokingYears: smokingStatus === 'current' ? randomInt(5, 40) : undefined,
        alcoholFrequency,
        alcoholDrinksPerWeek: getAlcoholDrinksPerWeek(alcoholFrequency),
        exerciseFrequency,
        exerciseMinutesPerWeek: exerciseFrequency === 'sedentary' ? 0 : randomInt(30, 300),
        diet: randomChoice(dietOptions),
        chiefComplaint: complaintData.complaint,
        symptomDuration: randomChoice(complaintData.durations),
    };
}

function generatePatient(index: number) {
    const patientId = `PT-${String(index + 1).padStart(5, '0')}`;
    const age = randomInt(18, 95);
    const sex = randomChoice(['male', 'female', 'male', 'male', 'female'] as const);
    const height = sex === 'male' ? randomInt(160, 195) : randomInt(150, 180);
    const weight = randomFloat(45, 150, 1);
    const bmi = Number.parseFloat((weight / Math.pow(height / 100, 2)).toFixed(1));
    const baseSystolic = 100 + (age * 0.5);
    const systolicBp = Math.min(200, Math.max(90, randomInt(Math.floor(baseSystolic - 10), Math.floor(baseSystolic + 30))));
    const diastolicBp = Math.min(120, Math.max(50, randomInt(60, 95)));
    const heartRate = randomInt(55, 100);
    const temperature = randomFloat(36, 37.5, 1);

    const conditions = generateConditions(age, bmi);
    const allergies = generateAllergies();
    const surgeries = generateSurgeries();
    const familyHistory = generateFamilyHistory();
    const conditionNames = conditions.map(c => c.condition.toLowerCase());
    const medications = generateMedications(conditionNames);

    return {
        patientId,
        demographics: { patientId, age, sex, weight, height, bmi, systolicBp, diastolicBp, heartRate, temperature },
        medicalHistory: { conditions, allergies, pastSurgeries: surgeries, familyHistory },
        medications,
        lifestyle: generateLifestyle(),
    };
}

// ==================== SEEDER FUNCTION ====================

export async function seedDemoData(count = 1000): Promise<void> {
    if (demoStorage.isInitialized()) {
        logger.info('Demo storage already initialized, skipping seed');
        return;
    }

    logger.info('Starting Demo Mode Patient Seeder', { count });

    const startTime = Date.now();
    let lowRisk = 0, mediumRisk = 0, highRisk = 0, criticalRisk = 0;

    for (let i = 0; i < count; i++) {
        const patientData = generatePatient(i);

        // Create patient
        const patient = demoStorage.createPatient({
            patientId: patientData.patientId,
            age: patientData.demographics.age,
            sex: patientData.demographics.sex,
            weight: patientData.demographics.weight,
            height: patientData.demographics.height,
            bmi: patientData.demographics.bmi,
            systolicBp: patientData.demographics.systolicBp,
            diastolicBp: patientData.demographics.diastolicBp,
            heartRate: patientData.demographics.heartRate,
            temperature: patientData.demographics.temperature,
        });

        // Create medical history
        demoStorage.createMedicalHistory({
            patientId: patient.id,
            conditions: patientData.medicalHistory.conditions,
            allergies: patientData.medicalHistory.allergies,
            pastSurgeries: patientData.medicalHistory.pastSurgeries,
            familyHistory: patientData.medicalHistory.familyHistory,
        });

        // Create medications
        for (const med of patientData.medications) {
            demoStorage.addMedication(patient.id, med);
        }

        // Create lifestyle
        demoStorage.createLifestyle({
            patientId: patient.id,
            smokingStatus: patientData.lifestyle.smokingStatus,
            smokingPacksPerDay: patientData.lifestyle.smokingPacksPerDay,
            smokingYears: patientData.lifestyle.smokingYears,
            alcoholFrequency: patientData.lifestyle.alcoholFrequency,
            alcoholDrinksPerWeek: patientData.lifestyle.alcoholDrinksPerWeek,
            exerciseFrequency: patientData.lifestyle.exerciseFrequency,
            exerciseMinutesPerWeek: patientData.lifestyle.exerciseMinutesPerWeek,
            diet: patientData.lifestyle.diet,
            chiefComplaint: patientData.lifestyle.chiefComplaint,
            symptomDuration: patientData.lifestyle.symptomDuration,
        });

        // Calculate risk for stats
        const riskScore = calculateRiskScore(patientData);
        if (riskScore >= 70) criticalRisk++;
        else if (riskScore >= 50) highRisk++;
        else if (riskScore >= 30) mediumRisk++;
        else lowRisk++;

        if ((i + 1) % 100 === 0) {
            logger.debug(`Generated ${i + 1}/${count} patients`);
        }
    }

    demoStorage.setInitialized(true);

    const elapsedTime = ((Date.now() - startTime) / 1000).toFixed(2);
    logger.info('Demo seeding complete', {
        count,
        elapsedSeconds: elapsedTime,
        riskDistribution: {
            low: lowRisk,
            medium: mediumRisk,
            high: highRisk,
            critical: criticalRisk,
        },
        totalPatients: demoStorage.getPatientCount(),
    });
}

interface SeedPatientData {
    demographics: { age: number; systolicBp: number; diastolicBp: number };
    medicalHistory: { conditions: Array<{ condition: string }> };
    medications: Array<{ genericName: string }>;
    lifestyle: { chiefComplaint: string; smokingStatus: string };
}

function calculateRiskScore(patient: SeedPatientData): number {
    let score = 0;

    if (patient.demographics.age > 75) score += 25;
    else if (patient.demographics.age > 65) score += 15;
    else if (patient.demographics.age > 55) score += 10;

    const conditionCount = patient.medicalHistory.conditions.length;
    if (conditionCount >= 5) score += 30;
    else if (conditionCount >= 3) score += 20;
    else if (conditionCount >= 1) score += 10;

    const medCount = patient.medications.length;
    if (medCount >= 8) score += 25;
    else if (medCount >= 5) score += 15;
    else if (medCount >= 3) score += 10;

    const criticalConditions = ['Coronary Artery Disease', 'Heart Failure', 'Chronic Kidney Disease Stage 4', 'COPD'];
    const hasCritical = patient.medicalHistory.conditions.some((c: { condition: string }) =>
        criticalConditions.some(cc => c.condition.includes(cc))
    );
    if (hasCritical) score += 25;

    const hasNitrate = patient.medications.some((m: { genericName: string }) => m.genericName === 'nitroglycerin');
    const chiefComplaint = (patient.lifestyle.chiefComplaint || '').toLowerCase();
    if (hasNitrate && (chiefComplaint.includes('erectile') || chiefComplaint.includes('ed '))) {
        score += 40;
    }

    if (patient.demographics.systolicBp >= 180 || patient.demographics.diastolicBp >= 120) score += 20;
    else if (patient.demographics.systolicBp >= 140 || patient.demographics.diastolicBp >= 90) score += 10;

    if (patient.lifestyle.smokingStatus === 'current') score += 15;

    return score;
}

export default seedDemoData;

